build_from:
  amd64: "jlesage/jdownloader-2:v26.08.2"
  aarch64: "jlesage/jdownloader-2:v26.08.2"
labels:
  org.opencontainers.image.title: "HAOS JDownloader"
  org.opencontainers.image.description: "JDownloader 2 as Home Assistant Add-on"
  org.opencontainers.image.source: "https://github.com/QozbroQqn/haos-addons/tree/main/jdownloader"
  org.opencontainers.image.licenses: "MIT license"
