build_from:
  amd64: "lscr.io/linuxserver/obsidian:amd64-v1.9.14-ls94"
  aarch64: "lscr.io/linuxserver/obsidian:arm64v8-v1.9.14-ls94"
labels:
  org.opencontainers.image.title: "HAOS Obsidian"
  org.opencontainers.image.description: "Obsidian as Home Assistant Add-on"
  org.opencontainers.image.source: "https://github.com/QozbroQqn/haos-addons/tree/main/obsidian"
  org.opencontainers.image.licenses: "MIT license"
